config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#news_feed'

  resources :users, only: :show do
    member do
      get :following, :followers
    end
    collection do
      get :search
    end
  end

  resources :posts do
    collection do
      get 'news_feed'
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "app/assets/images/default.jpg"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from ActionController::InvalidAuthenticityToken, with: :user_not_authenticated

  before_action :configure_permitted_parameters, if: :devise_controller?

  def render_404
    redirect_to(root_path)
  end

  def record_not_found
    flash[:alert] = 'Unable to find the records.'
    redirect_to(request.referer || root_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:avatar, :name, :username, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:avatar, :name, :username, :email, :password, :current_password)
    end
  end

  def user_not_authenticated
    redirect_to new_user_session_path, alert: "You need to sign in or sign up before continuing."
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to news_feed_posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def news_feed
    @posts = Post.where(user_id: current_user.following_ids + [current_user.id]).order(created_at: :desc)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_to search_users_path(query: params[:query])
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_to search_users_path(query: params[:query])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def search
    @users = User.where("name LIKE ? OR username LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connec8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <% if flash[:notice ]%>
    <p class='notice alert alert-success'><%= notice %></p>
    <% end %>
    <% if flash[:error]%>
      <p class='notice alert alert-danger'><%= flash[:error] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class='notice alert alert-danger'><%= flash[:alert] %></p>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, class: 'form-label' %>
    <%= f.text_area :body, class: 'form-control', rows: 5 %>
  </div>

  <%= f.submit 'Create Post', class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>News Feed</h1>

<% @posts.each do |post| %>
  <div class="post">
    <p><%= post.body %></p>
    <p>Posted by <%= post.user.username %> on <%= post.created_at.strftime("%B %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/news_feed.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>News Feed</h1>
    </div>
  </div>

  <div class="row mt-3 mb-3">
    <div class="col-12">
      <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
    </div>
  </div>

  <% @posts.each do |post| %>
    <div class="row mb-3">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><strong><%= post.user.name %></strong> (<%= post.user.username %>)</h5>
            <p class="card-text"><%= post.body %></p>
            <% if post.user == current_user %>
              <%= link_to "Edit", edit_post_path(post), class: "btn btn-primary" %> |
              <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/relationships/create.js.erb
$("#follow-btn").hide();
$("#unfollow-btn").show();

app/views/relationships/destroy.js.erb
$("#unfollow-btn").hide();
$("#follow-btn").show();

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Connec8</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
      <% if current_user%>
        <li class="nav-item">
          <%= link_to "News Feed", news_feed_posts_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search Users", search_users_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger ml-5' %>
        </li>
        <%else%>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary ml-5' %>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/users/search.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>Search Results</h1>
      <%= form_tag search_users_path, method: :get, class: "form-inline mt-3" do %>
        <%= text_field_tag :query, params[:query], placeholder: "Search by username", class: "form-control mr-sm-2" %>
        <%= submit_tag "Search", class: "btn btn-outline-success mt-2" %>
      <% end %>
    </div>
  </div>

  <div class="row mt-3">
  <div class="col-12">
    <% if @users.any? %>
      <ul class="list-group">
        <% @users.each do |user| %>
          <% if user != current_user %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= user.username %>
              <% if current_user.following?(user) %>
                <%= button_to "Unfollow", relationship_path(current_user.active_relationships.find_by(followed_id: user), query: params[:query]), method: :delete, class: "btn btn-danger", remote: true %>
              <% else %>
                <%= button_to "Follow", relationships_path(user_id: user, query: params[:query]), class: "btn btn-primary", remote: true %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <p>No users found.</p>
    <% end %>
  </div>
</div>

</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <div class="d-flex align-items-center">
        <%# <%= image_tag(@user.avatar.url(:thumb), class: "mr-3 rounded-circle", style: "width: 64px; height: 64px;") %>
        <h1><%= @user.name %></h1>
      </div>
      <p><strong>Username:</strong> <%= @user.username %></p>
    </div>
  </div>

  <div class="row mt-3 mb-3">
    <div class="col-12">
      <h2>Posts</h2>
      <% @posts.each do |post| %>
        <div class="card mb-3">
          <div class="card-body">
            <p class="card-text"><%= post.body %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>